# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'find_replace.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(293, 55)
        self.gridLayout_2 = QtWidgets.QGridLayout(widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.FRWidget = QtWidgets.QWidget(widget)
        self.FRWidget.setObjectName("FRWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.FRWidget)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.leFind = QtWidgets.QLineEdit(self.FRWidget)
        self.leFind.setPlaceholderText("")
        self.leFind.setObjectName("leFind")
        self.gridLayout.addWidget(self.leFind, 0, 0, 1, 1)
        self.btnPre = QtWidgets.QPushButton(self.FRWidget)
        self.btnPre.setObjectName("btnPre")
        self.gridLayout.addWidget(self.btnPre, 0, 1, 1, 1)
        self.btnNext = QtWidgets.QPushButton(self.FRWidget)
        self.btnNext.setObjectName("btnNext")
        self.gridLayout.addWidget(self.btnNext, 0, 2, 1, 1)
        self.leReplace = QtWidgets.QLineEdit(self.FRWidget)
        self.leReplace.setObjectName("leReplace")
        self.gridLayout.addWidget(self.leReplace, 1, 0, 1, 1)
        self.btnReplace = QtWidgets.QPushButton(self.FRWidget)
        self.btnReplace.setObjectName("btnReplace")
        self.gridLayout.addWidget(self.btnReplace, 1, 1, 1, 1)
        self.btnReplaceAll = QtWidgets.QPushButton(self.FRWidget)
        self.btnReplaceAll.setObjectName("btnReplaceAll")
        self.gridLayout.addWidget(self.btnReplaceAll, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.FRWidget, 0, 0, 1, 1)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Find and Replace"))
        self.btnPre.setToolTip(_translate("widget", "pre"))
        self.btnPre.setText(_translate("widget", "h"))
        self.btnNext.setToolTip(_translate("widget", "next"))
        self.btnNext.setText(_translate("widget", "i"))
        self.btnReplace.setToolTip(_translate("widget", "replace"))
        self.btnReplace.setText(_translate("widget", "P"))
        self.btnReplaceAll.setToolTip(_translate("widget", "replace all"))
        self.btnReplaceAll.setText(_translate("widget", "R"))
