# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'find_replace.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.FRWidget = QtWidgets.QWidget(widget)
        self.FRWidget.setObjectName("FRWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.FRWidget)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.le_find = QtWidgets.QLineEdit(self.FRWidget)
        self.le_find.setPlaceholderText("")
        self.le_find.setObjectName("le_find")
        self.gridLayout.addWidget(self.le_find, 0, 0, 1, 1)
        self.btn_pre = QtWidgets.QPushButton(self.FRWidget)
        self.btn_pre.setObjectName("btn_pre")
        self.gridLayout.addWidget(self.btn_pre, 0, 1, 1, 1)
        self.btn_next = QtWidgets.QPushButton(self.FRWidget)
        self.btn_next.setObjectName("btn_next")
        self.gridLayout.addWidget(self.btn_next, 0, 2, 1, 1)
        self.le_replace = QtWidgets.QLineEdit(self.FRWidget)
        self.le_replace.setObjectName("le_replace")
        self.gridLayout.addWidget(self.le_replace, 1, 0, 1, 1)
        self.btn_replace = QtWidgets.QPushButton(self.FRWidget)
        self.btn_replace.setObjectName("btn_replace")
        self.gridLayout.addWidget(self.btn_replace, 1, 1, 1, 1)
        self.btn_replace_all = QtWidgets.QPushButton(self.FRWidget)
        self.btn_replace_all.setObjectName("btn_replace_all")
        self.gridLayout.addWidget(self.btn_replace_all, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.FRWidget, 0, 0, 1, 1)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Find and Replace"))
        self.btn_pre.setToolTip(_translate("widget", "pre"))
        self.btn_pre.setText(_translate("widget", "h"))
        self.btn_next.setToolTip(_translate("widget", "next"))
        self.btn_next.setText(_translate("widget", "i"))
        self.btn_replace.setToolTip(_translate("widget", "replace"))
        self.btn_replace.setText(_translate("widget", "P"))
        self.btn_replace_all.setToolTip(_translate("widget", "replace all"))
        self.btn_replace_all.setText(_translate("widget", "R"))
