# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QssWindow(object):
    def setupUi(self, QssWindow):
        QssWindow.setObjectName("QssWindow")
        QssWindow.resize(665, 497)
        QssWindow.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QssWindow.setWindowIcon(icon)
        self.QssWidget = QtWidgets.QWidget(QssWindow)
        self.QssWidget.setMouseTracking(True)
        self.QssWidget.setObjectName("QssWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.QssWidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_top = QtWidgets.QWidget(self.QssWidget)
        self.widget_top.setMaximumSize(QtCore.QSize(16777215, 48))
        self.widget_top.setMouseTracking(True)
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_icon = QtWidgets.QLabel(self.widget_top)
        self.label_icon.setMouseTracking(True)
        self.label_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_icon.setObjectName("label_icon")
        self.horizontalLayout.addWidget(self.label_icon)
        self.btn_open = QtWidgets.QPushButton(self.widget_top)
        self.btn_open.setMouseTracking(True)
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout.addWidget(self.btn_open)
        self.btn_save = QtWidgets.QPushButton(self.widget_top)
        self.btn_save.setMouseTracking(True)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_title = QtWidgets.QLabel(self.widget_top)
        self.label_title.setMouseTracking(True)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout.addWidget(self.label_title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_attach = QtWidgets.QPushButton(self.widget_top)
        self.btn_attach.setMouseTracking(True)
        self.btn_attach.setCheckable(True)
        self.btn_attach.setChecked(True)
        self.btn_attach.setObjectName("btn_attach")
        self.horizontalLayout.addWidget(self.btn_attach)
        self.btn_min = QtWidgets.QPushButton(self.widget_top)
        self.btn_min.setMouseTracking(True)
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout.addWidget(self.btn_min)
        self.btn_close = QtWidgets.QPushButton(self.widget_top)
        self.btn_close.setMouseTracking(True)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout.addWidget(self.widget_top)
        self.editor = QssEditor(self.QssWidget)
        self.editor.setMouseTracking(True)
        self.editor.setObjectName("editor")
        self.verticalLayout.addWidget(self.editor)
        QssWindow.setCentralWidget(self.QssWidget)

        self.retranslateUi(QssWindow)
        QtCore.QMetaObject.connectSlotsByName(QssWindow)

    def retranslateUi(self, QssWindow):
        _translate = QtCore.QCoreApplication.translate
        QssWindow.setWindowTitle(_translate("QssWindow", "MainWindow"))
        self.label_icon.setText(_translate("QssWindow", "Q"))
        self.btn_open.setText(_translate("QssWindow", "open"))
        self.btn_save.setText(_translate("QssWindow", "save"))
        self.label_title.setText(_translate("QssWindow", "QSS Editor"))
        self.btn_attach.setText(_translate("QssWindow", "~"))
        self.btn_min.setText(_translate("QssWindow", "0"))
        self.btn_close.setText(_translate("QssWindow", "r"))
from sci.editor import QssEditor
from . import images_rc
